name: service
description: A module responsible for providing fine-grained business rules and
  business logic implementations.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  codenic_logger: ^1.0.1+1
  core:
    path: ../../core
  dartz: ^0.10.0
  domain:
    path: ../domain
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.11

dev_dependencies:
  build_runner: null
  json_serializable: ^4.1.3

flutter:
  module:
    androidX: true
    androidPackage: com.gcvh.service
    iosBundleIdentifier: com.gcvh.service
